trigger:
  - main
  - develop
  - feature/*
  - fix/*
  
pool:
  vmImage: ubuntu-latest
  
variables:
  buildConfiguration: 'Release'
  
stages:
- stage: DB_Build
  displayName: "Build Database DACPAC"
  dependsOn: []
  jobs:   
    - job: 'Build'
      steps:
      - task: UseDotNet@2
        displayName: 'Install dotnet 5.x'
        inputs:
          packageType: 'sdk'
          version: '5.x'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: 'restore'
          projects: 'src/**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build src/**/*.csproj'
        inputs:
          command: 'build'
          projects: 'src/**/*.csproj'
          arguments: '-c  $(buildConfiguration) --no-restore'

      - task: CopyFiles@2
        inputs:
          SourceFolder: 'src'
          Contents: '**/*.dacpac'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true
          preserveTimestamp: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish build artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Database DACPAC'
          publishLocation: 'Container'